name: 24-7 Aternos Bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & Run
        run: |
          npm install mineflayer
          timeout 21000s node index.js || echo "Restarting..."
          
